# Generated by Django 3.2.4 on 2021-07-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210715_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='decs',
        ),
    ]
